fraud:
  outputs:
    dev:
      account: wn29403.ap-southeast-3.aws
      database: AIRBYTE_DATABASE
      password: snowflake_bagus
      role: AIRBYTE_ROLE
      schema: prod
      threads: 1
      type: snowflake
      user: AIRBYTE_USER
      warehouse: AIRBYTE_WAREHOUSE
  target: dev
